# Hodor Project Level 0 by Julien Barbier
Canonical solution using Python 3 Urllib

Jupyter notebook, comments and explanation by Alexandro de Oliveira

This notebook is intended to be a reference on how to make a http POST request.
In order to run this notebook interactively, if you don't have Jupyter/IPython installed you can run a docker image with the following command:

In [ ]:
$ docker run -d -p 8888:8888 jupyter/minimal-notebook

Then the next step is to open your favorite browser and point it to localhost:8888 and enjoy your Jupyter installation.

*******

### POST Request  

In order to make our POST request in Python first we need to import the proper libraries:

In [1]:
import urllib.request
import urllib.parse

As you may noticed, when you import or assing value to variables we don't have any output form Jupyter interface.  
Let's define our URL:

In [2]:
url = "http://173.246.108.142/level0.php"

Now we are going to define the data to be sent in the body our POST request:

In [3]:
values = {
    "id" : "23", # Here goes your student id that will receive the vote.
    "holdthedoor" : "submit",
}

...and encode it to get proper byte string:

In [4]:
data = urllib.parse.urlencode(values)
data = data.encode('ascii') # data should be bytes

Here we are building our request with the URL and the data to be sent:

In [5]:
req = urllib.request.Request(url, data)

Sending our POST request:

In [6]:
with urllib.request.urlopen(req) as response:
    raw_response = response.read()
    html = response.readable()

Let's take a look at our output:

In [7]:
raw_response

b'\n<div id="message">\nI voted!\n</div>\n\n\n<h1>\nHold the Door challenge - Level 0\n</h1>\n\n<img src="http://173.246.108.142/h.jpg" width="500" />\n\n<p>\nVote 1024 times for your Holberton School id (i.e. 28 if you are Dora).\n</p>\n\n<h2>\nWho do you want to vote for?\n</h2>\n\n<form method="post">\n<input type="text" name="id" />\n<input type="submit" name="holdthedoor" />\n</form>\n\n<h2>\nResults\n</h2>\n\n    <table border="1">\n<tr>\n    <td>id</td><td># votes</td>\n</tr>\n<tr>\n    <td>\n1    </td>\n    <td>\n1774    </td>    \n</tr>\n<tr>\n    <td>\n10    </td>\n    <td>\n8    </td>    \n</tr>\n<tr>\n    <td>\n100    </td>\n    <td>\n134    </td>    \n</tr>\n<tr>\n    <td>\n1000    </td>\n    <td>\n1    </td>    \n</tr>\n<tr>\n    <td>\n1024    </td>\n    <td>\n41    </td>    \n</tr>\n<tr>\n    <td>\n108    </td>\n    <td>\n33    </td>    \n</tr>\n<tr>\n    <td>\n111    </td>\n    <td>\n4    </td>    \n</tr>\n<tr>\n    <td>\n112    </td>\n    <td>\n1045    </td>    \n</tr>\n<tr>\n    <td>\n113    </td>\n    <td>\n56    </td>    \n</tr>\n<tr>\n    <td>\n114    </td>\n    <td>\n1024    </td>    \n</tr>\n<tr>\n    <td>\n12121    </td>\n    <td>\n29    </td>    \n</tr>\n<tr>\n    <td>\n123112    </td>\n    <td>\n2    </td>    \n</tr>\n<tr>\n    <td>\n12344321    </td>\n    <td>\n1    </td>    \n</tr>\n<tr>\n    <td>\n1234432112344321    </td>\n    <td>\n2    </td>    \n</tr>\n<tr>\n    <td>\n1234567890    </td>\n    <td>\n30    </td>    \n</tr>\n<tr>\n    <td>\n124124    </td>\n    <td>\n1    </td>    \n</tr>\n<tr>\n    <td>\n1241245    </td>\n    <td>\n1    </td>    \n</tr>\n<tr>\n    <td>\n13    </td>\n    <td>\n1050    </td>    \n</tr>\n<tr>\n    <td>\n1337    </td>\n    <td>\n1340    </td>    \n</tr>\n<tr>\n    <td>\n14    </td>\n    <td>\n1029    </td>    \n</tr>\n<tr>\n    <td>\n147    </td>\n    <td>\n1054    </td>    \n</tr>\n<tr>\n    <td>\n148    </td>\n    <td>\n60    </td>    \n</tr>\n<tr>\n    <td>\n149    </td>\n    <td>\n19    </td>    \n</tr>\n<tr>\n    <td>\n150    </td>\n    <td>\n1025    </td>    \n</tr>\n<tr>\n    <td>\n151    </td>\n    <td>\n1234    </td>    \n</tr>\n<tr>\n    <td>\n158    </td>\n    <td>\n110    </td>    \n</tr>\n<tr>\n    <td>\n1580    </td>\n    <td>\n1020    </td>    \n</tr>\n<tr>\n    <td>\n1581    </td>\n    <td>\n1828    </td>    \n</tr>\n<tr>\n    <td>\n1582    </td>\n    <td>\n1024    </td>    \n</tr>\n<tr>\n    <td>\n1583    </td>\n    <td>\n8    </td>    \n</tr>\n<tr>\n    <td>\n1584    </td>\n    <td>\n9    </td>    \n</tr>\n<tr>\n    <td>\n1585    </td>\n    <td>\n1024    </td>    \n</tr>\n<tr>\n    <td>\n18    </td>\n    <td>\n3    </td>    \n</tr>\n<tr>\n    <td>\n2    </td>\n    <td>\n2402    </td>    \n</tr>\n<tr>\n    <td>\n20    </td>\n    <td>\n1    </td>    \n</tr>\n<tr>\n    <td>\n21    </td>\n    <td>\n1024    </td>    \n</tr>\n<tr>\n    <td>\n23    </td>\n    <td>\n913800    </td>    \n</tr>\n<tr>\n    <td>\n24    </td>\n    <td>\n1025    </td>    \n</tr>\n<tr>\n    <td>\n258    </td>\n    <td>\n1    </td>    \n</tr>\n<tr>\n    <td>\n28    </td>\n    <td>\n1027    </td>    \n</tr>\n<tr>\n    <td>\n3    </td>\n    <td>\n5    </td>    \n</tr>\n<tr>\n    <td>\n30    </td>\n    <td>\n1    </td>    \n</tr>\n<tr>\n    <td>\n33    </td>\n    <td>\n1039    </td>    \n</tr>\n<tr>\n    <td>\n34    </td>\n    <td>\n1039    </td>    \n</tr>\n<tr>\n    <td>\n369852    </td>\n    <td>\n10    </td>    \n</tr>\n<tr>\n    <td>\n37    </td>\n    <td>\n1025    </td>    \n</tr>\n<tr>\n    <td>\n3777    </td>\n    <td>\n1254    </td>    \n</tr>\n<tr>\n    <td>\n38    </td>\n    <td>\n1025    </td>    \n</tr>\n<tr>\n    <td>\n4    </td>\n    <td>\n3    </td>    \n</tr>\n<tr>\n    <td>\n40    </td>\n    <td>\n1024    </td>    \n</tr>\n<tr>\n    <td>\n41    </td>\n    <td>\n1024    </td>    \n</tr>\n<tr>\n    <td>\n42    </td>\n    <td>\n192208    </td>    \n</tr>\n<tr>\n    <td>\n43    </td>\n    <td>\n2    </td>    \n</tr>\n<tr>\n    <td>\n46    </td>\n    <td>\n1024    </td>    \n</tr>\n<tr>\n    <td>\n54    </td>\n    <td>\n7    </td>    \n</tr>\n<tr>\n    <td>\n666    </td>\n    <td>\n667    </td>    \n</tr>\n<tr>\n    <td>\n7    </td>\n    <td>\n1032    </td>    \n</tr>\n<tr>\n    <td>\n789    </td>\n    <td>\n4    </td>    \n</tr>\n<tr>\n    <td>\n789456123    </td>\n    <td>\n1    </td>    \n</tr>\n<tr>\n    <td>\n7913    </td>\n    <td>\n505    </td>    \n</tr>\n<tr>\n    <td>\n7914    </td>\n    <td>\n908    </td>    \n</tr>\n<tr>\n    <td>\n7915    </td>\n    <td>\n1034    </td>    \n</tr>\n<tr>\n    <td>\n7916    </td>\n    <td>\n1024    </td>    \n</tr>\n<tr>\n    <td>\n7917    </td>\n    <td>\n1870    </td>    \n</tr>\n<tr>\n    <td>\n7918    </td>\n    <td>\n220    </td>    \n</tr>\n<tr>\n    <td>\n7919    </td>\n    <td>\n1024    </td>    \n</tr>\n<tr>\n    <td>\n7920    </td>\n    <td>\n1024    </td>    \n</tr>\n<tr>\n    <td>\n7921    </td>\n    <td>\n1024    </td>    \n</tr>\n<tr>\n    <td>\n9    </td>\n    <td>\n1    </td>    \n</tr>\n<tr>\n    <td>\n9999999999    </td>\n    <td>\n1    </td>    \n</tr>\n</table>'

Not so beautiful...  
So, let's use a nice feature of Jupyter notebook and convert the raw response in pretty formatted HTML:

In [8]:
from IPython.core.display import display, HTML
display(HTML(raw_response.decode()))

Much better, right?  
*****
I hope you enjoyed this short introduction to POST requests!